services:
    oneup_contao_points_of_interest.dca_helper:
        class: Oneup\Contao\ContaoPointsOfInterestBundle\Dca\Helper
        public: true
        arguments:
            - '@security.token_storage'

    oneup_contao_points_of_interest.response_renderer:
        class: Oneup\Contao\ContaoPointsOfInterestBundle\PointsOfInterest\ResponseRenderer
        public: true

    oneup_contao_points_of_interest.image_size_provider:
        class: Oneup\Contao\ContaoPointsOfInterestBundle\Provider\ImageSizeProvider
        public: true
        arguments:
            - '@contao.image.sizes'
            - '@security.token_storage'

    oneup_contao_points_of_interest.content_element:
        class: Oneup\Contao\ContaoPointsOfInterestBundle\Controller\ContentElement\PointsOfInterest
        public: true
        arguments:
            - '@oneup_contao_points_of_interest.response_renderer'

    oneup_contao_points_of_interest.frontend_module:
        class: Oneup\Contao\ContaoPointsOfInterestBundle\Controller\FrontendModule\PointsOfInterest
        public: true
        arguments:
            - '@oneup_contao_points_of_interest.response_renderer'

