services:
    Oneup\Contao\ContaoPointsOfInterestBundle\Dca\Helper:
        arguments:
            - '@security.token_storage'

    Oneup\Contao\ContaoPointsOfInterestBundle\Controller\ContentElement\Poi:
        tags:
            - { name: contao.content_element, category: includes }

    Oneup\Contao\ContaoPointsOfInterestBundle\Controller\FrontendModule\Poi:
        tags:
            - { name: contao.frontend_module, category: miscellaneous }
